name: Build and Upload APK

on:
  push:
    branches:
      - main  # Adjust based on the branch you want to trigger the workflow from
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Build release APK
      - name: Build APK
        run: flutter build apk --release

      # Step 5: Upload APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk


      # Step 5: Push APK to a release branch
      - name: Push APK to releases branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b releases
          mkdir -p release-apks
          cp build/app/outputs/flutter-apk/app-release.apk release-apks/
          git add release-apks/app-release.apk
          git commit -m "Add release APK"
          git push origin releases --force
